USE home_db;

# THE FOLLOWING QUERY FIRST GETS SALARY IN DESC ORDER
# THEN ROW FUNC ASSIGNS 1ST TO HIGHEST SALARY AND GOES ON

# THE ROW FUNC GIVES NUMBERS AND IT DOES NOT MAKE SENSE TO USE 
# ROW NUMBERS WITHOUT ORDERING. ROW FUNC + ORDER BY MANDATORY

SELECT firstname, lastname, salary,
 ROW_NUMBER() OVER (ORDER BY salary DESC) FROM employee;
 
# GET 5TH HIGHEST SALARY
SELECT * FROM (SELECT firstname, lastname, salary,
 ROW_NUMBER() OVER (ORDER BY salary DESC) AS rownum
 FROM employee) TEMPTABLE WHERE rownum = 5;
 
# TO ASSIGN ROW NUMBER FOR PARTITIONS BASED ON EACH LOCATION
# FIRST PARTITION ON BASIS OF LOCATIONS
# THEN ASSIGN ROW NUMBER WITHIN EACH PARTITION
SELECT firstname, lastname, location, salary,
 ROW_NUMBER() OVER (PARTITION BY location ORDER BY salary DESC)
 FROM employee;

# GET HIGHEST SALARIES WITHIN EACH LOCATION
SELECT * FROM (SELECT firstname, lastname, location, salary,
 ROW_NUMBER() OVER (PARTITION BY location ORDER BY salary DESC)
  AS rownum FROM employee) TEMPTABLE WHERE rownum = 1;
  
