# ROW NUMBER CANNOT HANDLE DUPLICATES
# ORDER BY MANDATORY FOR RANK AND DENSE RANK
USE home_db;

SELECT firstname, lastname, salary,
 ROW_NUMBER() OVER (ORDER BY salary DESC) FROM employee;
 
SELECT firstname, lastname, salary,
 RANK() OVER (ORDER BY salary DESC) FROM employee;
 
SELECT firstname, lastname, salary,
 DENSE_RANK() OVER (ORDER BY salary DESC) FROM employee;
 
# FOR DUPLICATES SAME RANK IS ASSIGNED AND FOR NEXT ENTRY
# IT SKIPS THE RANK
# DENSE RANK DOES NOT SKIP ANY RANKS IN BETWEEN

# THERE IS SOME COMPETITION
# TOP 3 STUDENTS WHO SCORED THE HIGHEST MARKS
# 100,100,98,97,97,96
# FIND TOP 3 POSITIONS--> DENSE RANK